version: '3.8'

services:
  backend:
    build:
      context: ./src/app/backend
      dockerfile: Dockerfile
    container_name: soapbox-backend
    ports:
      - "8000:8000"
    volumes:
      - ./src/app/backend:/app
    networks:
      - soapbox-network

  frontend:
    build:
      context: ./src/app/frontend
      dockerfile: Dockerfile
    container_name: soapbox-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    volumes:
      - ./src/app/frontend:/app
    depends_on:
      - backend
    networks:
      - soapbox-network

networks:
  soapbox-network:
    driver: bridge
